apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: application-pipeline
spec:
  params:
    - default: deploy
      name: action
      type: string
    - default: pss
      name: department
      type: string
    - default: rtgs
      name: system
      type: string
    - default: dc
      name: location
      type: string
    - default: 'http://dashboard-hub-ns.apps.cluster-vtflb.vtflb.sandbox1105.opentlc.com/department/deploy/commit'
      name: callback_url
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/wael2000/dora'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:868966ef9d4b54952d8a74eb83bba40eb1f52c0148994fa704efd0e3797c61c5'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: deploy-app
      params:
        - name: SCRIPT
          value: sed -e 's/DEPARTMENT/$(params.department)/g' -e 's/SYSTEM/$(params.system)/g' -e 's/LOCATION/$(params.location)/g' gitops/applicationset.yaml | oc create -f - -n openshift-gitops
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: remove-app
      params:
        - name: SCRIPT
          value: sed -e 's/DEPARTMENT/$(params.department)/g' -e 's/SYSTEM/$(params.system)/g' -e 's/LOCATION/$(params.location)/g' gitops/applicationset.yaml | oc delete -f - -n openshift-gitops
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - remove
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: deploy-callback
      params:
        - name: system
          value: $(params.system)
        - name: callback_url
          value: $(params.callback_url)
        - name: status
          value: 'true'
      runAfter:
        - deploy-app
      taskRef:
        kind: Task
        name: deployment-callback
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
      workspaces:
        - name: workspace
          workspace: source
    - name: remove-callback
      params:
        - name: system
          value: $(params.system)
        - name: callback_url
          value: $(params.callback_url)
        - name: status
          value: 'false'
      runAfter:
        - remove-app
      taskRef:
        kind: Task
        name: deployment-callback
      when:
        - input: $(params.action)
          operator: in
          values:
            - remove
      workspaces:
        - name: workspace
          workspace: source
  workspaces:
    - name: source