kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
  #annotations:
  #  argocd.argoproj.io/sync-wave: "2"
data:
  build_tables.sql: |-
    alter table if exists Application 
       drop constraint if exists FKptjr8p27qnwtjpmknrmuyxlac;
    drop table if exists Application cascade;
    drop table if exists Config cascade;
    drop table if exists Department cascade;
    drop sequence if exists hibernate_sequence;

    create sequence hibernate_sequence start 1 increment 1;

    create table Application (
       id int8 not null,
        deployed boolean,
        description varchar(255),
        name varchar(255),
        department_id int8,
        primary key (id)
    );
    create table Config (
       id int8 not null,
        key varchar(255),
        value varchar(255),
        primary key (id)
    );

    create table Department (
       id int8 not null,
        aws boolean,
        azure boolean,
        dc boolean,
        description varchar(255),
        name varchar(255),
        provider varchar(255),
        status varchar(255),
        tenantType varchar(255),
        primary key (id)
    );

    alter table if exists Application 
      add constraint FKptjr8p27qnwtjpmknrmuyxlac 
      foreign key (department_id) 
      references Department;


  create_database.sql: CREATE DATABASE fsi;
  config.sql: insert into config (id,key,value) values (1,'dblocation','DC');
  data.sql: |-
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (1,'Payment and settlement','pss','deprived','ns',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (2,'Treasury','treasury','deprived','cluster',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (3,'Customer Service','cs','deprived','ns',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (4,'Compliance and Legal','legal','deprived','nodes',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (5,'Marketing','marketing','deprived','ns',false,false,false);

    insert into Application (id,name,description,deployed,department_id) values (1,'RTGS','Real-Time Gross Settlement System',false,1);
    insert into Application (id,name,description,deployed,department_id) values (2,'ACH','Automated Clearing House System',false,1);
    insert into Application (id,name,description,deployed,department_id) values (3,'EFT','Electronic Funds Transfer System',false,1);
    insert into Application (id,name,description,deployed,department_id) values (4,'PG','EPayment Gateways',false,1);

    insert into Application (id,name,description,deployed,department_id) values (5,'TMS','Treasury Management System',false,2);
    insert into Application (id,name,description,deployed,department_id) values (6,'CMS','Cash Management System',false,2);
    insert into Application (id,name,description,deployed,department_id) values (7,'IVS','Investment Management System',false,2);
    insert into Application (id,name,description,deployed,department_id) values (8,'FX','Foreign Exchange Management System',false,2);
    insert into Application (id,name,description,deployed,department_id) values (9,'LMS','Liquidity Management System',false,2);

    insert into Application (id,name,description,deployed,department_id) values (10,'CRM','Customer Relationship Management System',false,3);
    insert into Application (id,name,description,deployed,department_id) values (12,'CC','Contact Center System',false,3);

    insert into Application (id,name,description,deployed,department_id) values (13,'GRC','Governance, Risk, and Compliance System',false,4);
    insert into Application (id,name,description,deployed,department_id) values (14,'AML','Anti-Money Laundering System',false,4);
    insert into Application (id,name,description,deployed,department_id) values (15,'KYC','Know Your Customer System',false,4);
